name: Conan CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-10.15, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Conan
      id: conan
      uses: ./ # Uses an action in the root directory

    - name: Conan version
      run: echo "Conan version was '${{ steps.conan.outputs.version }}'"

    - name: Set dynamic variable
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          echo "conan-default" >> $CONAN_PRESET
        else
          echo "conan-release" >> $CONAN_PRESET
        fi
      shell: bash

    - name: Conan profile
      working-directory: ${{github.workspace}}
      run: conan profile detect

    - name: Conan install
      working-directory: ${{github.workspace}}
      run: conan install . --build=missing

    - name: CMake preset
      working-directory: ${{github.workspace}}
      run: cmake --preset ${{env.CONAN_PRESET}}

    - name: CMake build
      working-directory: ${{github.workspace}}
      # Build your program with the given configuration
      run: cmake --build --preset ${{env.CONAN_PRESET}}

    - name: CTest
      working-directory: ${{github.workspace}}
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --preset ${{env.CONAN_PRESET}}
      
